#!/bin/bash

source config


# Make sure the source directory exists
if [ ! -d "${RASPI_PROJECT_FOLDER}" ]; then
  echo "The source folder ${RASPI_PROJECT_FOLDER} does not exist!"
  exit 1
fi

# Remove the Raspberry Pi project folder
ssh debian@beaglebone.local ssh pi@raspberrypi.local rm -rf /home/pi/python

# Copy the Raspberry Pi project folder to a temporary folder on the BeagleBone
ssh debian@beaglebone.local mkdir /home/debian/cache
rsync -auv "${RASPI_PROJECT_FOLDER}/" debian@beaglebone.local:/home/debian/cache/raspi

# Check if successful
if [ $? -eq 0 ]; then
    echo "Transferred files to BeagleBone"
else
    echo "Failed to transfer files. Is the BeagleBone connected?"
    exit
fi

# Copy the Raspberry Pi project folder from the temporary folder to the Raspberry Pi
ssh debian@beaglebone.local rsync -auv /home/debian/cache/raspi/ pi@raspberrypi.local:/home/pi/python

# Check if successful
if [ $? -eq 0 ]; then
    echo "Transferred files to Raspberry Pi"
else
    echo "Failed to transfer files. Is the Raspberry Pi connected?"
fi

# Remove the BeagleBone-side cached copy
ssh debian@beaglebone.local rm -rf /home/debian/cache/raspi
